### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid character (CR or LF) found in method name

### ISSUE THREAD

**Issue by ghost** [selakavon/spring-rest-oauth2-mongo#5]
I am simply running this code on the 8080, by commenting the logic on properties file

java.lang.IllegalArgumentException: Invalid character (CR or LF) found in method name

```
2017-09-12 01:55:56.181  INFO 21432 --- [nio-8080-exec-3] o.a.coyote.http11.Http11NioProcessor     : Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character (CR or LF) found in method name
	at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:228) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_144]
```

![image](https://user-images.githubusercontent.com/8208031/30295474-5d67f0f2-975e-11e7-9888-25215341c857.png)

**Comment by selakavon** [comment]
I guess you're copy-pasting the command from github and it's pasted with new-line characters. That's why the command line is responding before the end of your command.
Try to edit your command in notepad first to avoid new-line chars.
Or use another client or another shell (i.e. cygwin)
